name: Build the package 
on:
  workflow_dispatch: []
  push:
    paths-ignore:
      - 'docs/**'      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      cuda_compiler_version: 11
      PREFIX: distr
      CPU_COUNT: 4
      RUN_TESTS: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set the environment
        run: |
          conda update conda
          $CONDA/bin/conda env create -f scripts/mapd-deps-conda-dev-env.yml --force
      - name: Install nvidia-cuda-toolkit
        run: |
          conda install -n omnisci-dev -c conda-forge cudatoolkit-dev arrow-cpp-proc=3.0.0=cuda
        if: ${{ env.cuda_compiler_version != 'None' }}
      - name: Build
        run: |
          mkdir -p ${{ env.PREFIX }}
          rm -rf build
          $CONDA/bin/conda run -n omnisci-dev bash scripts/conda/build-install-all.sh
      - name: Test
        run: |
          BINPATH=$(cd ${{ env.PREFIX }}/bin; pwd -P)
          cd build
          mkdir -p tmp
          $CONDA/bin/conda run -n omnisci-dev $BINPATH/initdb tmp
          $CONDA/bin/conda run -n omnisci-dev make sanity_tests
          rm -rf tmp
      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: result_packages
          path: ${{ env.PREFIX }}
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: build/*.log
