name: Build
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV

  push:
    paths-ignore:
      - 'docs/**'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check stlye
        run: |
          find . -name ThirdParty -prune -or \( -name '*.cpp' -or -name '*.h' \) | xargs clang-format --dry-run --Werror -style=file

  build:
    uses: ./.github/workflows/build.yml
    with:
      cuda_compiler_version: None

  build-cuda:
    uses: ./.github/workflows/build.yml
    with:
      cuda_compiler_version: 11

  test:
    needs: build
    uses: ./.github/workflows/test.yml

