name: Build package
on:
  push:
    paths-ignore:
      - 'docs/**'      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      cuda_compiler_version: None
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          $CONDA/bin/conda env create -f scripts/mapd-deps-conda-dev-env.yml
          $CONDA/bin/conda run -n omnisci-dev bash scripts/conda/build-install-all.sh
      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: result_packages
          path: $CONDA/conda-bld/linux-64/*
