name: "Build package and docs, push docs to Pages"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      cuda_compiler_version: None
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build
      - name: Build
        run: |
          $CONDA/bin/conda init
          $CONDA/bin/conda env create -f scripts/mapd-deps-conda-dev-env.yml 
          $CONDA/bin/conda activate omnisci-dev
          bash scripts/conda/build-install-all.sh
      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: result_packages
          path: $CONDA/conda-bld/linux-64/*
      - name: Install doxygen deps
        run: sudo apt install -y doxygen graphviz plantuml
      - name: Make Doxygen docs
        working-directory: build
        run: |
          cmake ../docs
          make doxygen
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Setup requirements
        working-directory: docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Sphinx docs
        working-directory: docs
        run: |
          sed -i "/segment_analytics/s/^#//" source/conf.py
          make html
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@main
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_WRITE_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/build/html # The folder the action should deploy.
          BUILD_SCRIPT: touch build/html/.nojekyll
