name: Build
on:
  workflow_dispatch: []
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      cuda_compiler_version: None

  build-cuda:
    uses: ./.github/workflows/build.yml
    with:
      cuda_compiler_version: 11

