name: Build the package [SH]
on:
  workflow_dispatch
jobs:
  build:
    runs-on: [self-hosted]
    env:
      cuda_compiler_version: None
      PREFIX: distr
      CPU_COUNT: 4
      RUN_TESTS: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set the environment
        run: |
          $CONDA/bin/conda env create -f scripts/mapd-deps-conda-dev-env.yml --force
      - name: Build
        run: |
          mkdir -p ${{ env.PREFIX }}
          rm -rf build
          $CONDA/bin/conda run -n omnisci-dev bash scripts/conda/build-install-all.sh
      - name: Test
        run: |
          BINPATH=$(cd ${{ env.PREFIX }}/bin; pwd -P)
          cd build
          mkdir -p tmp
          $CONDA/bin/conda run -n omnisci-dev $BINPATH/initdb tmp
          $CONDA/bin/conda run -n omnisci-dev make sanity_tests
          rm -rf tmp
      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: result_packages
          path: ${{ env.PREFIX }}
